name: Heroku Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # get code repo
      - name: Checkout code
        uses: actions/checkout@main
      # install NodeJS
      - name: Use Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
      # build the app. CI (continuous integration build) runs npm install, npm build and npm test
      - name: Continuous Integration Build
        run: npm ci
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "shop--shop"
          heroku_email: "nicnolen@ymail.com"


