name: Heroku Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # get code from repo
      - name: Checkout code
        uses: actions/checkout@main
      # install NodeJS
      - name: Use Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
      # build the app. CI (Continuous Integration) runs npm install, npm test and npm build
      - name: run Continuous Integration
        run: npm install
      - name: build
        run: npm run build
      - name: run tests
        run: npm run test
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "shop--shop"
          heroku_email: "nicnolen@ymail.com"
